# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "play-with-go.dev"
email:
description: > # this means to ignore newlines until "baseurl:"
  play-with-go.dev

baseurl: # the subpath of your site, e.g. /blog
url: "https://play-with-go.dev" # the base hostname & protocol for your site

#sidebar
default-image: https://play-with-go.dev/images/playgo.png # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

guides-categories:
  - "Start here"
  - "Next steps"
  - "What's coming in Go 1.16"

#footer
built-by: The play-with-go.dev Authors
copyright:
   name: The play-with-go.dev Authors
   link: 'https://github.com/play-with-go/play-with-go/blob/main/LICENSE'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/
toc:
  min_level: 1
  max_level: 2

# Tracker
analytics: G-7Z9WCLBZNJ

highlighter: rouge


#social
# facebook:
# twitter:
github: https://github.com/play-with-go/play-with-go
# twitter_username:
# youtube:

# Sass style
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-toc]

# Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-toc


#sdkbaseurl: http://localhost:8080
sdkbaseurl: https://unpkg.com/pwd-sdk@0.0.12
pwdurl: http://localhost
controllerurl: http://localhost:8081/guides

exclude:
  - "docs"
  - "*.go"
  - "*.mod"
  - "*.sum"
  - "docker/"
  - "guides/"
  - "*.sh"
  - "*.cue"
  - "*.yml"
  - "CONTRIBUTING.md"


